# Generated by Django 4.0.3 on 2023-11-30 09:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_0002_user_mobile_0002_user_mobile_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challanges',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('problemstatement', models.TextField()),
                ('sample_input_1', models.TextField()),
                ('sample_input_2', models.TextField()),
                ('output', models.TextField()),
                ('explanations', models.TextField()),
                ('language', models.CharField(choices=[('1', 'Python'), ('2', 'Java'), ('3', 'CPP')], default='1', max_length=10)),
                ('stack', models.CharField(choices=[('1', 'frontend'), ('2', 'backtend')], max_length=20)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
