# Generated by Django 4.0.3 on 2023-11-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_challenges_alter_user_managers_delete_challanges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='stack',
            field=models.CharField(choices=[('1', 'Frontend'), ('2', 'Backtend'), ('3', 'FullStack'), ('4', 'AI/ML'), ('5', 'Data Analyst'), ('6', 'Data Science')], max_length=20),
        ),
    ]
